name: release suite
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: build
        run: cargo build -r --bin game
      - name: release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: github action release test
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1.4.2
        with:
          ndk-version: r25c
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: add android target
        run: rustup target add aarch64-linux-android
      - name: install cargo apk
        run: cargo install cargo-apk
      - name: build android
        run: cargo apk build --target aarch64-linux-android --lib
