name: Rust

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "ui/**"
      - ".github/workflows/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "data/**"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  linux_build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --locked --bin game
    - name: Run tests
      run: cargo test --locked --all-targets --features solver

  linux_solver_test:
    needs: linux_build_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Run
      run: cargo run --locked --release --features solver --bin solver -- --check



  windows_build_test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --locked --bin game
    - name: Run tests
      run: cargo test --locked --all-targets --features solver

  macos_build_test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --locked --bin game
    - name: Run tests
      run: cargo test --locked --all-targets --features solver

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: clippy
      run: cargo clippy --locked --all-targets --features solver -- -D warnings
    - name: formatting
      run: cargo fmt --check
